package chj.idler.dao;

import chj.idler.dataobject.EpisodeDO;

public interface EpisodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insert(EpisodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insertSelective(EpisodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    EpisodeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKeySelective(EpisodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table episode
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKey(EpisodeDO record);
}