package chj.idler.dao;

import chj.idler.dataobject.VideoDO;

public interface VideoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insert(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insertSelective(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    VideoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKeySelective(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKey(VideoDO record);
}