package chj.idler.dao;

import chj.idler.dataobject.VideoUpdateDO;

public interface VideoUpdateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insert(VideoUpdateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insertSelective(VideoUpdateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    VideoUpdateDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKeySelective(VideoUpdateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_update
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKey(VideoUpdateDO record);
}