package chj.idler.dao;

import chj.idler.dataobject.VideoDO;

import java.util.List;

public interface VideoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    int insert(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    int insertSelective(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    VideoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    int updateByPrimaryKeySelective(VideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    int updateByPrimaryKey(VideoDO record);
    VideoDO selectByDetailUrl(String detailUrl);
    List<VideoDO> selectAll();

}