package chj.idler.dao;

import chj.idler.dataobject.VideoSubDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoSubDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    int insert(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    int insertSelective(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    VideoSubDO selectByPrimaryKey(@Param("userId") Integer userId, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    int updateByPrimaryKeySelective(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Thu May 21 11:52:31 CST 2020
     */
    int updateByPrimaryKey(VideoSubDO record);

    List<Integer> selectVideoIdByUserId(Integer userId);
    Byte selectSub(@Param("userId")Integer userId,@Param("videoId") Integer videoId);
    List<Integer>selectSubVideoId(Integer videoId);
}