package chj.idler.dao;

import chj.idler.dataobject.VideoSubDO;
import org.apache.ibatis.annotations.Param;

public interface VideoSubDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insert(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int insertSelective(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    VideoSubDO selectByPrimaryKey(@Param("userId") Integer userId, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKeySelective(VideoSubDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sub
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    int updateByPrimaryKey(VideoSubDO record);
}