package chj.idler.dataobject;

public class EpisodeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.title
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.url
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.status
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.video_id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.now
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Integer now;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.finish
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Byte finish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.picture
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.create_time
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.id
     *
     * @return the value of episode.id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.id
     *
     * @param id the value for episode.id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.title
     *
     * @return the value of episode.title
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.title
     *
     * @param title the value for episode.title
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.url
     *
     * @return the value of episode.url
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.url
     *
     * @param url the value for episode.url
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.status
     *
     * @return the value of episode.status
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.status
     *
     * @param status the value for episode.status
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.video_id
     *
     * @return the value of episode.video_id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.video_id
     *
     * @param videoId the value for episode.video_id
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.now
     *
     * @return the value of episode.now
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Integer getNow() {
        return now;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.now
     *
     * @param now the value for episode.now
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setNow(Integer now) {
        this.now = now;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.finish
     *
     * @return the value of episode.finish
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Byte getFinish() {
        return finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.finish
     *
     * @param finish the value for episode.finish
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setFinish(Byte finish) {
        this.finish = finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.picture
     *
     * @return the value of episode.picture
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.picture
     *
     * @param picture the value for episode.picture
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.create_time
     *
     * @return the value of episode.create_time
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.create_time
     *
     * @param createTime the value for episode.create_time
     *
     * @mbg.generated Wed Jun 03 23:05:11 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}