package chj.idler.dataobject;

public class EpisodeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.sequence
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Short sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.url
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.status
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column episode.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.id
     *
     * @return the value of episode.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.id
     *
     * @param id the value for episode.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.sequence
     *
     * @return the value of episode.sequence
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Short getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.sequence
     *
     * @param sequence the value for episode.sequence
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setSequence(Short sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.url
     *
     * @return the value of episode.url
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.url
     *
     * @param url the value for episode.url
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.status
     *
     * @return the value of episode.status
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.status
     *
     * @param status the value for episode.status
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column episode.video_id
     *
     * @return the value of episode.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column episode.video_id
     *
     * @param videoId the value for episode.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
}