package chj.idler.dataobject;

import java.util.Date;

public class VideoUpdateDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_update.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_update.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_update.day
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_update.time
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_update.id
     *
     * @return the value of video_update.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_update.id
     *
     * @param id the value for video_update.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_update.video_id
     *
     * @return the value of video_update.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_update.video_id
     *
     * @param videoId the value for video_update.video_id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_update.day
     *
     * @return the value of video_update.day
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_update.day
     *
     * @param day the value for video_update.day
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_update.time
     *
     * @return the value of video_update.time
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_update.time
     *
     * @param time the value for video_update.time
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}