package chj.idler.dataobject;

public class VideoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name2
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.detail_url_crc
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private Long detailUrlCrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.detail_url
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String detailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.image
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.description
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.source
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.type
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.tags
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.score
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    private Integer publishYear;
    public Integer getPublishYear() {
        return publishYear;
    }

    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name2
     *
     * @return the value of video.name2
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name2
     *
     * @param name2 the value for video.name2
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setName2(String name2) {
        this.name2 = name2 == null ? null : name2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.detail_url_crc
     *
     * @return the value of video.detail_url_crc
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public Long getDetailUrlCrc() {
        return detailUrlCrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.detail_url_crc
     *
     * @param detailUrlCrc the value for video.detail_url_crc
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setDetailUrlCrc(Long detailUrlCrc) {
        this.detailUrlCrc = detailUrlCrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.detail_url
     *
     * @return the value of video.detail_url
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getDetailUrl() {
        return detailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.detail_url
     *
     * @param detailUrl the value for video.detail_url
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl == null ? null : detailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.image
     *
     * @return the value of video.image
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.image
     *
     * @param image the value for video.image
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.description
     *
     * @return the value of video.description
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.description
     *
     * @param description the value for video.description
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.source
     *
     * @return the value of video.source
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.source
     *
     * @param source the value for video.source
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.type
     *
     * @return the value of video.type
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.type
     *
     * @param type the value for video.type
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.tags
     *
     * @return the value of video.tags
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.tags
     *
     * @param tags the value for video.tags
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.score
     *
     * @return the value of video.score
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.score
     *
     * @param score the value for video.score
     *
     * @mbg.generated Sat May 23 20:54:20 CST 2020
     */
    public void setScore(Double score) {
        this.score = score;
    }
}