package chj.idler.dataobject;

public class VideoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.img
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.end
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Byte end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.source
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    private Byte source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.img
     *
     * @return the value of video.img
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.img
     *
     * @param img the value for video.img
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.end
     *
     * @return the value of video.end
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Byte getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.end
     *
     * @param end the value for video.end
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setEnd(Byte end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.source
     *
     * @return the value of video.source
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.source
     *
     * @param source the value for video.source
     *
     * @mbg.generated Tue May 12 16:52:41 CST 2020
     */
    public void setSource(Byte source) {
        this.source = source;
    }
}